### ISSUE TITLE
The notification system crash

### ISSUE THREAD

**Issue by Luigi1992** [Luigi1992/quick-study#57]
When executing the code, the notification system crashes without quitting the application, but it must be avoided such a thing. This is the error code:

Activity com.gcwrome2014.quickstudy.ExamsActivity has leaked ServiceConnection com.gcwrome2014.quickstudy.notification.ScheduleClient$1@41fe69a0 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.gcwrome2014.quickstudy.ExamsActivity has leaked ServiceConnection com.gcwrome2014.quickstudy.notification.ScheduleClient$1@41fe69a0 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:979)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:873)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1649)
            at android.app.ContextImpl.bindService(ContextImpl.java:1632)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:518)
            at com.gcwrome2014.quickstudy.notification.ScheduleClient.doBindService(ScheduleClient.java:38)
            at com.gcwrome2014.quickstudy.ExamsActivity.onCreate(ExamsActivity.java:186)
            at android.app.Activity.performCreate(Activity.java:5395)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5072)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by alicjab** [comment]
Thanks, I'm working on it
